server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: spring-boot-quartz
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 20000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: JDBC
    jdbc:
      initialize-schema: NEVER

hellojobCron: '0/2 * * * * ?'

logging:
  config: classpath:logback.xml
